# Generated by Django 6.0.5 on 2026-05-31 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_land_acres', models.FloatField()),
                ('trees_possible', models.IntegerField()),
                ('co2_absorbed_kg_year', models.FloatField()),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('aqi_category', models.CharField(blank=True, max_length=50, null=True)),
                ('dominant_pollutant', models.CharField(blank=True, max_length=50, null=True)),
                ('tiles_analyzed', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='pollution.querylog')),
            ],
        ),
    ]
